apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-bot
  template:
    metadata:
      labels:
        app: chat-bot
    spec:
      containers:
      - name: chat-bot
        image: chat-bot:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000  
    nodePort: 30002
  selector:
    app: chat-bot